### ISSUE TITLE
PyHIST hard dependency on pixman version 0.36.0

### ISSUE THREAD

**Issue by juanfranciscomorales** [manuel-munoz-aguirre/PyHIST#27]
Hello,

We are trying to install PyHIST in our cluster, however we are not able to do it because of a hard dependency on pixman version 0.36.0. We are wondering why this hard dependency on an older pixman version exists and if it can be upgraded to the latest version.

Thank you in advance,

Francisco

**Comment by manuel-munoz-aguirre** [comment]
Hi Francisco,
PyHIST depends on OpenSlide (which depends on pixman), and at some point there were issues with specific pixman versions (0.38 if I recall correctly) that prevented SVS regions from loading properly (see for example [here](https://github.com/openslide/openslide/issues/291)). Version 0.36.0 was not affected by this issue and that's why it was included as a hard dependency. Although I have not tried with the newer version yet, it seems that it should work fine.

**Comment by juanfranciscomorales** [comment]
Thank you for your replay.

Best,

Francisco
